"""
Bot Manager V2 - Main Flask Application
AI-powered bot generation and GitHub deployment system
"""
from flask import Flask, render_template, request, jsonify, session
from flask_cors import CORS
import uuid
import json
import logging
from datetime import datetime

from utils.config import Config
from utils.bot_generator import BotGenerator
from utils.github_deployer import GitHubDeployer

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize Flask app
app = Flask(__name__)
app.secret_key = Config.SECRET_KEY
CORS(app)

# Initialize components
bot_generator = BotGenerator()
github_deployer = GitHubDeployer()

# In-memory session storage (use Redis in production)
sessions = {}

@app.route('/')
def index():
    """Serve the main chat interface"""
    return render_template('index.html')

@app.route('/api/generate', methods=['POST'])
def generate_bot():
    """
    Generate bot code from natural language prompt
    Expected JSON: {"prompt": "user description", "bot_type": "chatbot"}
    """
    try:
        data = request.get_json()
        prompt = data.get('prompt', '').strip()
        bot_type = data.get('bot_type', 'chatbot')
        session_id = data.get('session_id', str(uuid.uuid4()))
        
        if not prompt:
            return jsonify({
                'success': False,
                'error': 'Prompt cannot be empty'
            }), 400
        
        logger.info(f"Generating bot for prompt: {prompt[:100]}...")
        
        # Generate bot code
        result = bot_generator.generate_bot_code(prompt, bot_type)
        
        # Store in session
        if session_id not in sessions:
            sessions[session_id] = {}
        sessions[session_id]['last_generation'] = result
        
        return jsonify({
            'success': True,
            'session_id': session_id,
            'files': result.get('files', {}),
            'metadata': result.get('metadata', {}),
            'message': 'Bot generated successfully! Ready to deploy to GitHub.'
        })
        
    except Exception as e:
        logger.error(f"Generation error: {str(e)}")
        return jsonify({
            'success': False,
            'error': f"Generation failed: {str(e)}"
        }), 500

@app.route('/api/deploy', methods=['POST'])
def deploy_to_github():
    """
    Deploy generated bot to GitHub
    Expected JSON: {"session_id": "xxx", "repo_name": "my-bot", "description": "..."}
    """
    try:
        data = request.get_json()
        session_id = data.get('session_id')
        repo_name = data.get('repo_name', '').strip()
        description = data.get('description', 'Bot generated by Bot Manager V2')
        commit_message = data.get('commit_message', 'Initial bot deployment')
        
        if not session_id or session_id not in sessions:
            return jsonify({
                'success': False,
                'error': 'Invalid or expired session. Please generate a bot first.'
            }), 400
        
        if not repo_name:
            return jsonify({
                'success': False,
                'error': 'Repository name is required'
            }), 400
        
        # Get generated files
        generation = sessions[session_id].get('last_generation')
        if not generation or not generation.get('files'):
            return jsonify({
                'success': False,
                'error': 'No generated files found. Please generate a bot first.'
            }), 400
        
        logger.info(f"Deploying {repo_name} to GitHub...")
        
        # Create repository
        repo_result = github_deployer.create_repository(repo_name, description)
        
        if repo_result.get('error'):
            return jsonify({
                'success': False,
                'error': f"Repository creation failed: {repo_result['error']}"
            }), 500
        
        # Push files
        deploy_result = github_deployer.push_files(
            repo_name=repo_name,
            files=generation['files'],
            commit_message=commit_message
        )
        
        if deploy_result.get('success'):
            # Clear session after successful deployment
            sessions.pop(session_id, None)
            
            return jsonify({
                'success': True,
                'repository_url': deploy_result.get('repository'),
                'files_deployed': deploy_result.get('files', []),
                'message': f'Successfully deployed to {deploy_result.get("repository")}'
            })
        else:
            return jsonify({
                'success': False,
                'error': deploy_result.get('error', 'Unknown deployment error')
            }), 500
        
    except Exception as e:
        logger.error(f"Deployment error: {str(e)}")
        return jsonify({
            'success': False,
            'error': f"Deployment failed: {str(e)}"
        }), 500

@app.route('/api/preview', methods=['POST'])
def preview_bot():
    """Preview generated bot without deploying"""
    try:
        data = request.get_json()
        session_id = data.get('session_id')
        
        if not session_id or session_id not in sessions:
            return jsonify({
                'success': False,
                'error': 'Invalid session'
            }), 400
        
        generation = sessions[session_id].get('last_generation')
        if not generation:
            return jsonify({
                'success': False,
                'error': 'No generated bot found'
            }), 400
        
        # Return HTML content for preview
        html_content = generation['files'].get('index.html', '<h1>No HTML generated</h1>')
        
        return jsonify({
            'success': True,
            'html': html_content,
            'metadata': generation.get('metadata', {})
        })
        
    except Exception as e:
        logger.error(f"Preview error: {str(e)}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/api/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    config_errors = Config.validate()
    
    return jsonify({
        'status': 'healthy',
        'timestamp': datetime.now().isoformat(),
        'config_status': 'valid' if not config_errors else 'missing_keys',
        'config_errors': config_errors,
        'active_sessions': len(sessions)
    })

if __name__ == '__main__':
    # Validate configuration on startup
    errors = Config.validate()
    if errors:
        logger.warning(f"Configuration warnings: {errors}")
    
    app.run(
        host='0.0.0.0',
        port=5000,
        debug=Config.DEBUG
    )